import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { BRAND } from "@/lib/brand";
import { COMPANY } from "@/lib/company";
import {
  buildReportPreviewContent,
  type ReportApiData,
} from "@/lib/report-content";
import { formatDate } from "@/lib/utils";
import type { Report } from "@/types";

const C = {
  primary: [...BRAND.primaryRgb] as [number, number, number],
  tableHead: [82, 94, 136] as [number, number, number],
  ink: [26, 31, 46] as [number, number, number],
  inkMuted: [139, 146, 160] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
} as const;

export async function generateReportPDF(
  report: Report,
  data: ReportApiData
): Promise<void> {
  const content = buildReportPreviewContent(report, data);
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  doc.setFillColor(...C.primary);
  doc.rect(0, 0, pageWidth, 34, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...C.white);
  doc.text(COMPANY.name, margin, 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(220, 226, 240);
  doc.text(COMPANY.productName, margin, 18);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...C.white);
  doc.text(content.title, margin, 27);

  y = 42;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.inkMuted);
  doc.text(content.subtitle, margin, y);
  y += 6;

  const meta = [
    `Report No: ${report.reportNo}`,
    `Created: ${formatDate(report.createdAt)}`,
    `Period: ${formatDate(report.dateFrom)} – ${formatDate(report.dateTo)}`,
  ];
  meta.forEach((line) => {
    doc.text(line, margin, y);
    y += 5;
  });
  y += 4;

  if (content.metrics.length) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...C.ink);
    doc.text("Key Metrics", margin, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["Metric", "Value"]],
      body: content.metrics.map((metric) => [metric.label, metric.value]),
      theme: "grid",
      headStyles: {
        fillColor: C.tableHead,
        textColor: C.white,
        fontStyle: "bold",
        fontSize: 8,
      },
      bodyStyles: { fontSize: 8, textColor: C.ink },
      alternateRowStyles: { fillColor: [248, 249, 252] },
    });

    y =
      (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ??
      y + 20;
    y += 8;
  }

  content.tables.forEach((table) => {
    if (y > 250) {
      doc.addPage();
      y = margin;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...C.ink);
    doc.text(table.title, margin, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [table.headers],
      body: table.rows,
      theme: "grid",
      headStyles: {
        fillColor: C.tableHead,
        textColor: C.white,
        fontStyle: "bold",
        fontSize: 8,
      },
      bodyStyles: { fontSize: 8, textColor: C.ink },
      alternateRowStyles: { fillColor: [248, 249, 252] },
    });

    y =
      (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ??
      y + 20;
    y += 8;
  });

  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.inkMuted);
  doc.text(
    `Generated by ${COMPANY.productName} · ${COMPANY.contact.website}`,
    margin,
    pageHeight - 8
  );

  doc.save(`${report.reportNo}.pdf`);
}
